price = float(input("Enter the price of the item: "))
tax_rate = float(input("Enter the sales tax rate (in %): "))
final_price = price + (price * tax_rate / 100)
print(f"The final price including tax is: {final_price}")
print("Name: KUNAL DUA")
print("Roll Number: 35614802722")
